### PR TITLE
[MNT-19456] get node metadata test client to manage input parameter

### PR DESCRIPTION
**Pull request by alessandrobenedetti**
This patch attempts to make the test SolrAPI client more realistic.

### CODE REVIEW

**Comment by alessandrobenedetti** [comment]
Hi @michaelsuzukisagi , I reverted the imports optimisations and added the comment.
Let me know if it is ok now !
The reason of the process metadata is to make sure that if a metadata is explictly set to NOT being included, it must not returned.
If not the test Client will not behave as the real one, causing invisible bugs in the code that calls the test client , staying silent.
Let me know if you need any additional clarification!

**Comment by agazzarini** [comment]
Assigned for review to @tpage-alfresco because he is following the other PR/MR related with the issue

**Comment by tpage-alfresco** [comment]
The only comment I have is that the method name is a bit vague. Otherwise LGTM.

Sorry the review took a while to get around to.

**Comment by agazzarini** [comment]
Hi @tpage-alfresco since the method mutes the state of the input parameter we could use a fluent approach changing the signature to return it. Something like 

`public NodeMetadata processNodeMetadata(...)
`    

about the name, do you have any suggestion? I'm happy to change that if that results in a better understanding.

**Comment by tpage-alfresco** [comment]
Maybe something like `removeUnrequestedMetadata` or something?

**Pull request merged**
